# Qa Configuration

# API Configuration

# DB Configuration
awsAurora:
  host: "cs-aws-aurora-db-sapi-uat-lcd39k.internal-83uhjy.usa-e1.cloudhub.io"

# Aws Bucket Name
s3:
  bucketName: "coolsys-mssql-aurora-uat-private"
  
# Mail Summary  
outlook:
  recipients: ["developmenterrors@coolsys.com","guransh.chaudhary@caeliusconsulting.com"]
  
# AWS Tables
tables:
  serviceCalls: "service_calls_test"
  hvacServiceItems: "hvac_service_items_test"
  hvacMaterials: "hvac_materials"
  hvacAppointments: "hvac_appointments_test" 