# Dev Configuration


# DB Configuration
awsAurora:
  host: "cs-aws-aurora-db-sapi-dev-uy0wfu.83uhjy.usa-e1.cloudhub.io"


# S3 Configuration
s3:
  bucketName: "coolsys-mssql-aurora-private"
 
outlook:
  recipients: ["guransh.chaudhary@caeliusconsulting.com"]
  
tables:
  serviceCalls: "service_calls_v3"
  hvacServiceItems: "hvac_service_items_v3"
  hvacMaterials: "hvac_materials_v3"
  hvacAppointments: "hvac_appointments_v3"
  
api:
  id: "21051358"